### ISSUE TITLE
v 0.0.3 not available in Thonny package manager or UPIP

### ISSUE THREAD

**Issue by andywarburton** [pimoroni/phew#20]
Trying to work with 0.0.3 to get access point support but both methods (UPIP and Thonny) only give me 0.0.2

Does 0.0.3 need to be "pushed" to these services or is there a way for me to request this version specifically?

**Comment by Gadgetoid** [comment]
Fixed. Though it looks like we're due an 0.0.4!

**Comment by andywarburton** [comment]
Ooooooooh! Exciting!

**Comment by andywarburton** [comment]
Thanks for the fix!
