### ISSUE TITLE
Request: publish as a library

### ISSUE THREAD

**Issue by andypiper** [pimoroni/phew#3]
Could this be pushed to pypi so it is straightforward to install via `upip` or in Thonny's package manager? 🙂

**Comment by lowfatcode** [comment]
Yes absolutely. It's not a process I'm familiar with so pinging @Gadgetoid for some input!

**Comment by Gadgetoid** [comment]
Boom - https://pypi.org/project/micropython-phew/

**Comment by andypiper** [comment]
Fab, will be giving this a proper test drive shortly 🙏🏻

**Comment by SoongJr** [comment]
I found this via pypi, so it has had some success already 😁 And it has saved me a lot of effort, I was not expecting to be finished with [my prometheus client implementation](https://github.com/SoongJr/pi-pico/blob/7046ca962b6d07bbda1c9029d5355877b9df69f0/main.py) in just a couple hours and 20 lines of code, so thanks for this module!  
Starred⭐ and Watched👁
