### ISSUE TITLE
Change location of log file

### ISSUE THREAD

**Issue by tocomolo** [pimoroni/phew#34]
Hello, is there any way to change the file location of the log file?
I'm aware that you can modify the variable in [logging.py](https://github.com/pimoroni/phew/blob/main/phew/logging.py), but is there any way to do this without changing the module's code?

Thanks!

**Comment by lslezak** [comment]
You can change the log location from your code:

```python
from phew import server, logging
logging.log_file = "server.log"
```

**Comment by tocomolo** [comment]
This worked thank you!! I'm a bit of a python noob so I didn't relize that you could do that from within your code!
