### ISSUE TITLE
Issues with Phew logfile truncation on Enviro Grow 

### ISSUE THREAD

**Issue by retropangy** [pimoroni/phew#6]
After a number of days uptime Enviro Grow boards stop responding until log.txt and log.txt.tmp are delated - they stop logging and cannot even be put into provisioning mode again. On checking via a connected laptop the error appears to be in the Phew logging.py truncate routine - the following appears when trying to run main.py;

Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "enviro/init.py", line 159, in startup
  File "phew/phew/logging.py", line 37, in truncate
NameError: local variable referenced before assignment

Once log.txt and log.txt.tmp are removed main.py can be started.

(Logged here rather than in enviro repo as issue appears to be Phew related - apologies if incorrect location!)

**Comment by Gadgetoid** [comment]
I think this is a bug:

https://github.com/pimoroni/phew/blob/acf33ad6627aecc9dd2b432916600450d5aedc3d/phew/logging.py#L24-L25

`chunk` is only set if `discard > 0`, but a `discard == 0` could pass this check and result in `chunk.find` being called on an uninitialized variable.

Though it sounds like in your case `discard` should *not* be zero.

**Comment by retropangy** [comment]
Applied change to logging.py - will confirm if still running in a few days.

**Comment by retropangy** [comment]
Just to confirm it appears to be working fine.
