### ISSUE TITLE
Need to allow white space after the {{ and before the }}

### ISSUE THREAD

**Issue by kevinmcaleer** [pimoroni/phew#8]
https://github.com/pimoroni/phew/blob/8995e8b822ab3daa2e33c90e83b7d1191d3442a5/phew/template.py#L25

I built a couple of templates using the `{{ render_template("header.html") }}` and it ignored them because of the whitespace before and after the `render_template()` call. I guessed this was the case and corrected my code to remove the whitespace: `{{render_template("header.html")}}`.

It would be nice to be more tolerant of the white space - we could add a `.strip()` function to enable this.

**Comment by lowfatcode** [comment]
Fixed in https://github.com/pimoroni/phew/commit/243229f619c169497c8da3807bd26572d8559782
