### ISSUE TITLE
log truncation does not work

### ISSUE THREAD

**Issue by SoongJr** [pimoroni/phew#9]
Love the module, but after two days the file system on my Pi Pico W was full. /log.txt was taking up quite some storage:
```
>>> os.stat('/log.txt')
(32768, 0, 0, 0, 0, 0, 788944, 1609466686, 1609466686, 1609466686)
```
(that's 800kB I believe)

It contains a line once for every REST request iphew received:

> 2021-01-01 02:03:45 [info     /  131200] > GET /metrics (200 OK) [293ms]
> 2021-01-01 02:04:00 [info     /  125104] > GET /metrics (200 OK) [293ms]
> 2021-01-01 02:04:16 [info     /  119008] > GET /metrics (200 OK) [293ms]
> 2021-01-01 02:04:31 [info     /  112912] > GET /metrics (200 OK) [495ms]
> 2021-01-01 02:04:46 [info     /  106816] > GET /metrics (200 OK) [428ms]

My program: https://github.com/SoongJr/pi-pico/blob/7046ca962b6d07bbda1c9029d5355877b9df69f0/main.py

I looked at [the phew code](https://github.com/pimoroni/phew/blob/main/phew/logging.py) and it clearly states "the defaults values are designed to limit the log to at most three blocks on the Pico". The code looks to me like it's trying to truncate at 11kB, which my file exceeds, so it's not working.

I have to go to work now, will look into this further in the evening, but maybe someone has an idea.

**Comment by lowfatcode** [comment]
that's odd, we're using on Enviro and it's truncating log files fine - have you done a pull recently? I did rework the truncation logic a couple of days ago in this commit: https://github.com/pimoroni/phew/commit/a21bc19fe817840589f63246d9bf3e31f378d7e1

**Comment by SoongJr** [comment]
Ah, I'm installing with upip:
> Installing micropython-phew 0.0.2 from https://files.pythonhosted.org/packages/18/8d/c3323d6d7e17c95e8e94b2c9fb96d88a8cbbd2c45c65f909b276c78761c2/micropython-phew-0.0.2.tar.gz
But I was _looking_ at the code. Just noticed the changelog in today''s release [v0.0.3](https://github.com/pimoroni/phew/releases/tag/v0.0.3), was not aware that truncation wasn't automatic before.

Rightfully closed I believe, that's what I call fast solutions! 😜
